services:
  test-backend:
    image: nginx:latest
  test-proxy:
    image: mataeragon/simple-nginx-ssl-proxy:latest
    ports:
      - "443:443"
    environment:
      - BACKEND_HOST=test-backend
      - BACKEND_PORT=80
      - PROXY_HOSTNAME=localhost